version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(levelname)s - %(message)s"
  error:
    format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  info_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: info.log
    mode: w
  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: error
    filename: error.log
    mode: w
root:
  level: INFO
  handlers: [console, info_file_handler]
  propagate: no
loggers:
  main:
    level: INFO
    handler: [console, error_file_handler]
    propagate: no
